# Generated by Django 3.2.13 on 2022-06-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('aadhar', models.CharField(max_length=16)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=256)),
                ('pincode', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('primary_phone', models.CharField(max_length=15)),
                ('other_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('resume_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenEducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_board', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('education_specialization', models.CharField(max_length=255)),
                ('year_of_passing', models.IntegerField()),
                ('institute', models.CharField(max_length=255)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='citizen', to='api.citizen')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
